### ISSUE TITLE
default_currency ignored when nullable

### ISSUE THREAD

**Issue by synotna** [django-money/django-money#138]
The default_currency option is ignored by the admin when the field is nullable

value = MoneyField(max_digits=10, decimal_places=2, default_currency='USD', blank=True, null=True)

The default_currency will not be selected by default

I spent some time figuring out how to make it happen, seems to be a lot harder than it sounds!

**Comment by listingmirror** [comment]
I have also hit this, very annoying

**Comment by Stranger6667** [comment]
Thank you for the report! I'll look at this issue

**Comment by listingmirror** [comment]
PR coming momentairly

**Comment by listingmirror** [comment]
@Stranger6667  Bah it is tricky.. constructor of MoneyField does not deal with nullable right

**Comment by Stranger6667** [comment]
@listingmirror @synotna @benjaoming 
#209 Should fix this issue. Please check if you have time

**Comment by listingmirror** [comment]
@Stranger6667 did not fix. This is how my model is defined:

    sale_price = MoneyField(max_digits=10, decimal_places=2, default_currency='USD', null=True)


My form is just a ModelForm with nothing fancy.

In my database I have the 

   sale_price = Null
   sale_price_currency = 'USD'


I go to the edit page, and the sale_price box is empty, but CAD is selected in the dropdown

**Comment by Stranger6667** [comment]
Very strange. I have following setup:

```

class NullMoneyFieldModel(models.Model):
    field = MoneyField(max_digits=10, decimal_places=2, default_currency='USD', null=True)




class NullableModelForm(forms.ModelForm):

    class Meta:
        model = NullMoneyFieldModel
        fields = ('field', )

```

And I created the following row in the database:
```
INSERT INTO testapp_nullmoneyfieldmodel VALUES (1, 'USD', NULL);
```

Edit page (http://127.0.0.1:8000/admin/testapp/nullmoneyfieldmodel/1/change/)

![screen](https://cloud.githubusercontent.com/assets/1236561/16689534/b8baf6a4-4523-11e6-932a-eceb3f1ee215.png)


Django 1.9.7

**Comment by Stranger6667** [comment]
It is not merged yet, did you check  ``nullable-default_currency`` branch?

**Comment by listingmirror** [comment]
@Stranger6667 Okay I backed out my custom widget and I confirmed your fix worked.  I had a custom widget going on that must have another issue (which is my fault, not django-money).. for what it's worth, my widget is like:


    class CustomMoneyWidget(MoneyWidget):
      def format_output(self, rendered_widgets):
        return ('<div class="row">'
                '<div class="col-xs-12 col-sm-8">%s</div>'
                '<div class="col-xs-12 col-sm-4">%s</div>'
                '</div>') % tuple(rendered_widgets)
