### ISSUE TITLE
Field._has_changed is deprecated

### ISSUE THREAD

**Issue by msgre** [django-money/django-money#206]
Hello, I get warning about using some deprecated Django 1.10 internals during tests of my application:
```
/usr/local/lib/python3.5/site-packages/djmoney/forms/fields.py:90: RemovedInDjango110Warning: `Field._has_changed` is deprecated, use `has_changed` instead.
/usr/local/lib/python3.5/site-packages/djmoney/forms/fields.py:111: RemovedInDjango110Warning: `Field._has_changed` is deprecated, use `has_changed` instead.
```
Tried `django-money` from Pypi, and also recent version directly from GitHub (`pip install -e git+https://github.com/django-money/django-money#egg=django-money`). Django 1.9.5, Python 3.5.1.

**Comment by Stranger6667** [comment]
Hello, @msgre 
Can you provide some code examples?
I'll submit some changes, that should fix this

**Comment by msgre** [comment]
Hello @Stranger6667, you are faster than me, sorry :)

It seems that there is more places, where `djmoney` access `_has_changed`:

```
$ grep -riI _has_changed ./*
./forms/widgets.py:    # Needed for Django 1.5.x, where Field doesn't have the '_has_changed' method.
./forms/widgets.py:    if hasattr(TextInput, '_has_changed'):  # noqa
./forms/widgets.py:        def _has_changed(self, initial, data):
./forms/widgets.py:            if amount_widget._has_changed(amount_initial, amount_data):
./forms/widgets.py:            if currency_widget._has_changed(currency_initial, currency_data) and amount_data:
./forms/fields.py:        if VERSION < (1, 10) and hasattr(amount_field, '_has_changed') and hasattr(currency_field, '_has_changed'):
./forms/fields.py:            amount_field.has_changed = amount_field._has_changed
./forms/fields.py:            currency_field.has_changed = currency_field._has_changed
./forms/fields.py:        _has_changed = has_changed
```

I find that that deprecated message came from [this condition](https://github.com/django-money/django-money/blob/664fa3ffa1ac4d523abc88ec8ba0e1638403c547/djmoney/forms/fields.py#L44-L46). I don't go deep into `djmoney` logic (so I don't know if it is safe to change that condition), but if I changed it in my case, deprecated messages disappear:

```
if VERSION < (1, 10) and hasattr(amount_field, '_has_changed') and hasattr(currency_field, '_has_changed'):
    amount_field.has_changed = amount_field.has_changed
    currency_field.has_changed = currency_field.has_changed
```

**Comment by Stranger6667** [comment]
Can you check it again with latest djmoney version from repository? It should be fixed in 664fa3f

**Comment by msgre** [comment]
My latest comment above was applied on `664fa3f` (I update package to latest version and issue wasn't solved; so I debug it and found that reference to condition).

**Comment by Stranger6667** [comment]
So, this code was not required for Django 1.8+:

```
if VERSION < (1, 8) and hasattr(amount_field, '_has_changed') and hasattr(currency_field, '_has_changed'):
            amount_field.has_changed = amount_field._has_changed
            currency_field.has_changed = currency_field._has_changed
```

Now it is removed and everything should be OK

**Comment by benjaoming** [comment]
@Stranger6667 where was it removed? You mean the issue is now fixed?

**Comment by msgre** [comment]
@Stranger6667 I could confirm that `Field._has_changed is deprecated` nessage is gone after your last modification in [180548f](https://github.com/django-money/django-money/commit/180548f9284a6091ce77f9505da592fc673e8fe2) commit.

Thanks.

**Comment by msgre** [comment]
@benjaoming Yes. Reported deprecation message is gone, see https://github.com/django-money/django-money/commit/180548f9284a6091ce77f9505da592fc673e8fe2

**Comment by Stranger6667** [comment]
@msgre @benjaoming 
So, if the issue was fixed I'll close this issue and update the changelog
