### ISSUE TITLE
'too many values to unpack' for readonly moneyfield

### ISSUE THREAD

**Issue by yellow-sky** [django-money/django-money#232]
python 2.7.12
django 1.9.9
django-money 9.1

If you add MoneyField in the list of readonly fields then:

```
ValueError at /admin/nextgis_payments/invoice4managerroproxy/15/change/

Request Method:     GET
Request URL:    http://127.0.0.1:8000/admin/nextgis_payments/invoice4managerroproxy/15/change/
Django Version:     1.9.9
Exception Type:     ValueError
Exception Value:    

too many values to unpack

Exception Location:     /home/yellow/Project/NextGisId/env/lib/python2.7/site-packages/django/utils/numberformat.py in format, line 38
```

**Comment by Stranger6667** [comment]
Hello! Thank you for the report!
Could you please provide some code examples for this error?

**Comment by yellow-sky** [comment]
Hi!
My sample project:
https://github.com/yellow-sky/DjMoneyTest

Migration will create sample data.

Working admin page (writable admin):
http://127.0.0.1:8001/admin/test_admin_panel/simplemoneymodel/1/change/

Not wotrking page (ro admin):
http://127.0.0.1:8001/admin/test_admin_panel/simplemoneymodelproxy/1/change/   

! Please note: 
https://github.com/yellow-sky/DjMoneyTest/blob/master/DjMoneyTest/settings.py#L108

**Comment by benjaoming** [comment]
I guess this would be the snippet that causes the problem... and thanks for sharing the full project btw!!

```
# ReadOnly admin pages
@admin.register(SimpleMoneyModelProxy)
class ROAdmin(admin.ModelAdmin):
    readonly_fields = ['pay',]
```

**Comment by Stranger6667** [comment]
It is another problem with combining of different localization types (Django and pymoneyed). For example: 
"руб.48.00" - Russian ruble has 2 dots in localized string and app fails with:

```python
 int_part, dec_part = str_number.split('.') 

too many values to unpack
```
@benjaoming 
I think we should do something with our admin integration. It is related to #220

**Comment by Stranger6667** [comment]
Hi @yellow-sky !
The issue should be fixed now in the master branch.

**Comment by omargawdat** [comment]
Hello the issue is still here in Arabic format, when the filed is readonly 
<img width="508" alt="image" src="https://github.com/user-attachments/assets/83eba66b-e769-4622-a6ac-f3d2b684fdaf">
